== 스터디 그룹

=== 생성

operation::create-study-group[snippets='http-request,request-headers,request-parts,request-parameters,http-response,response-headers,response-body,response-fields']
'''

=== 전체조회

operation::get-study-groups[snippets='http-request,request-headers,request-parameters,http-response,response-headers,response-body,response-fields']
'''

=== 마이 페이지 조회

operation::get-my-study-groups[snippets='http-request,request-headers,request-parameters,http-response,response-headers,response-body,response-fields']
'''

=== 상세조회

operation::get-study-group-detail[snippets='http-request,request-headers,path-parameters,http-response,response-headers,response-body,response-fields']
'''

=== 수정

operation::update-study-group[snippets='http-request,request-headers,request-parts,request-parameters,http-response,response-headers,response-body,response-fields']
'''

=== 삭제

operation::delete-study-group[snippets='http-request,request-headers,path-parameters,http-response,response-headers']
'''
